---
- name: Install Redmica
  hosts: all
  become: true
  vars:
    selinux_state: disabled

  roles:
    - role: geerlingguy.repo-epel
      tags: repo-epel
    - role: robertdebock.selinux
      tags: selinux
    - role: mamono210.locale
      tags: locale
    - role: mamono210.timezone
      tags: timezone
    - role: mamono210.httpd_install
      tags: httpd
    - role: mamono210.goaccess_install
      tags: goaccess_install
    - role: mamono210.goaccess_systemd
      tags: goaccess_systemd
    - role: mamono210.ruby
      tags: ruby
    - role: mamono210.postgresql
      tags: postgresql
    - role: redmine/create-pg-account-and-database
      tags: database
    - role: mamono210.redmine_install
      tags: redmine_install
    - role: mamono210.swapfile
      tags: swapfile
    - role: mamono210.passenger
      tags: passenger
    - role: redmine/passenger
      tags: redmine_passenger
    - role: mamono210.redmine_themes
      tags: redmine_themes
    - role: mamono210.redmine_facts
      tags: redmine_facts
