---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Setup Selenium container
      community.docker.docker_container:
        name: selenium
        image: selenium/standalone-firefox:latest
        ports:
          - '4444:4444'
        state: started

    - name: Execute
      ansible.builtin.include_role:
        name: mamono210.molecule_ec2_driver
      vars:
        molecule_ec2_driver_resource_state: 'present'
