---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Execute
      ansible.builtin.include_role:
        name: mamono210.molecule_test_ec2
      vars:
        molecule_test_ec2_resource_state: 'absent'
