---
- name: Clean up
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: set_fact molecule_platforms
      set_fact:
        molecule_platforms: "{{ molecule_yml.platforms }}"

    - name: Execute
      ansible.builtin.include_role:
        name: mamono210.awsiam
      vars:
        aws_access_key: "{{ molecule_platforms.0.aws_access_key }}"
        aws_secret_key: "{{ molecule_platforms.0.aws_secret_key }}"
        aws_region: "{{ molecule_platforms.0.aws_region }}"
        awsiam_user: "{{ molecule_platforms.0.awsiam_user }}"
        awsiam_user_state: absent
