---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    aws_access_key: ${AWS_ACCESS_KEY_ID_1}
    aws_secret_key: ${AWS_SECRET_ACCESS_KEY_1}
    linux_group: circleci
    linux_user: circleci
    linux_userhome: /home/circleci
    aws_region: ap-northeast-1
    awsiam_user: ${AWSIAM_USER}
    awsiam_policy_file_path: molecule.json
    awsiam_policy_name: ${AWSIAM_POLICY_NAME}
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - cleanup
    - converge
    - verify
    - cleanup
