---
- name: Install prerequisites
  ansible.builtin.yum:
    name:
      - curl-devel
      - gcc
      - gcc-c++
      - httpd-devel
      - openssl-devel
      - zlib-devel
    state: present

- name: Check if Passenger is installed
  ansible.builtin.command: passenger -v
  register: passenger_installed
  changed_when: False
  ignore_errors: True

- name: Install Passenger
  community.general.gem:
    name: passenger
    include_doc: no
    user_install: no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: passenger_installed is failed

- name: Copy the file to be used for swap
  ansible.builtin.command: dd if=/dev/zero of=/swap bs=1M count=1024
  when:
    - passenger_installed is failed
    - passenger_swap | bool

- name: Format the file for swap
  ansible.builtin.command: mkswap /swap
  when:
    - passenger_installed is failed
    - passenger_swap | bool

- name: Add the file to the system as a swap file
  ansible.builtin.command: swapon /swap
  when:
    - passenger_installed is failed
    - passenger_swap | bool

- name: Run the Passenger Apache module installer
  ansible.builtin.command: |
    passenger-install-apache2-module --auto --languages ruby
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: passenger_installed is failed

- name: Register results of showing configuration snippet command to variable
  ansible.builtin.command: passenger-install-apache2-module --snippet
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: passenger_snippet_vars
  when: passenger_installed is failed

- name: Create redmine.conf
  ansible.builtin.template:
    src: redmine.conf
    dest: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
    mode: 0755
  notify: restart Apache
  when: passenger_installed is failed
